spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:h2:~/liquibase2;DB_CLOSE_ON_EXIT=TRUE
    username: sa
  liquibase:
    change-log: classpath:db/dbchangelog.xml
  h2:
    console:
      enabled: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

server:
  servlet:
    context-path: /${spring.application.name}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
